### PR TITLE
Tell EEUMM to include the links

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by shlomif** [comment]
Thanks @szabgab ! I merged it into html-t5-dev, but it made the build fail (locally on mageia 8):

```
[shlomif@telaviv1 html-tidy5]$ bash -x ~/conf/build/perl/install-to-apps-perl-modules.sh
+ b_pl=Build.PL
+ prefix=/home/shlomif/apps/perl/modules
+ test -e Build.PL
+ perl Makefile.PL PREFIX=/home/shlomif/apps/perl/modules
Failed to clean-up 2 metadata. Errors:
Expected a map structure from string or file. (prereqs -> configure -> x_Alien::TidyHTML5) [Validation: 2]
Expected a map structure from string or file. (prereqs -> configure -> x_Alien::Base::Wrapper) [Validation: 2]
Expected a map structure from string or file. (prereqs -> configure -> x_Devel::CheckLib) [Validation: 2]
 at /usr/share/perl5/ExtUtils/MM_Any.pm line 1225.
Failed to clean-up 2 metadata. Errors:
Expected a map structure from string or file. (prereqs -> configure -> x_Alien::TidyHTML5) [Validation: 2]
Expected a map structure from string or file. (prereqs -> configure -> x_Devel::CheckLib) [Validation: 2]
Expected a map structure from string or file. (prereqs -> configure -> x_Alien::Base::Wrapper) [Validation: 2]

```

**Comment by szabgab** [comment]
That looks very strange.
What version of perl and ExtUtils::MakeMaker do you have?

**Comment by shlomif** [comment]
@szabgab : sorry for the late reply - I got distracted:

```
[shlomif@telaviv1 html-tidy5]$ perl -v

This is perl 5, version 32, subversion 0 (v5.32.0) built for x86_64-linux-thread-multi
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2020, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

[shlomif@telaviv1 html-tidy5]$ perl -MExtUtils::MakeMaker\ 9999
ExtUtils::MakeMaker version 9999 required--this is only version 7.44.
BEGIN failed--compilation aborted.
[shlomif@telaviv1 html-tidy5]$ which perl
/usr/bin/perl
[shlomif@telaviv1 html-tidy5]$
```

**Comment by szabgab** [comment]
I really don't know. I have EUMM 7.50 and perl 5.30 and it works fine.
I see a somewhat similar bug report here: https://rt.cpan.org/Public/Bug/Display.html?id=121924 but it was resolved.
Another one here suggests all kinds of upgrades to fix this issue: https://stackoverflow.com/questions/25751777/using-cpanm-to-install-packages-comes-up-with-errors-version-hash-is-not-a

**Comment by shlomif** [comment]
> I really don't know. I have EUMM 7.50 and perl 5.30 and it works fine.
> I see a somewhat similar bug report here: https://rt.cpan.org/Public/Bug/Display.html?id=121924 but it was resolved.
> Another one here suggests all kinds of upgrades to fix this issue: https://stackoverflow.com/questions/25751777/using-cpanm-to-install-packages-comes-up-with-errors-version-hash-is-not-a

I now tried it in a new(ish) user account with perlbrew perl v5.30.3 on fedora 33 x86-64 and it still happens.

**Comment by szabgab** [comment]
Now I am even more confused. I don't even know how I got to this repository.
I just checked and this module was last released by Petdance https://metacpan.org/release/HTML-Tidy5 and it has the links to GitHub.
I thought I saw this module somehow on CPAN released by you.

**Comment by shlomif** [comment]
@szabgab : this is the repo of https://metacpan.org/pod/HTML::T5 , which is a fork of H-Tidy5 (featuring an Alien::*-based build sys mostly).

**Comment by szabgab** [comment]
Yeah, so then solution is probably in the HTML::Tidy as that has the link properly included in the META.json file

**Comment by shlomif** [comment]
merged. closing.

**Pull request closed without merging**
